/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABbutton: typeof import('@arco-design/web-vue')['Bbutton']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AFonfigProvider: typeof import('@arco-design/web-vue')['FonfigProvider']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    DropdownDropdown: typeof import('./src/components/dropdown/dropdown.vue')['default']
    IconCopy: typeof import('@arco-design/web-vue/es/icon')['IconCopy']
    IconDown: typeof import('@arco-design/web-vue/es/icon')['IconDown']
    IconFolder: typeof import('@arco-design/web-vue/es/icon')['IconFolder']
    IconImport: typeof import('@arco-design/web-vue/es/icon')['IconImport']
    IconPaste: typeof import('@arco-design/web-vue/es/icon')['IconPaste']
    IconRedo: typeof import('@arco-design/web-vue/es/icon')['IconRedo']
    IconUndo: typeof import('@arco-design/web-vue/es/icon')['IconUndo']
    IconUpload: typeof import('@arco-design/web-vue/es/icon')['IconUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIconSvgIcon: typeof import('./src/components/svgIcon/svgIcon.vue')['default']
  }
}
