/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ContextMenuContextMenu: typeof import('./src/components/contextMenu/ContextMenu.vue')['default']
    ContextMenuContextMenuGroup: typeof import('./src/components/contextMenu/ContextMenuGroup.vue')['default']
    ContextMenuContextMenuIconCheck: typeof import('./src/components/contextMenu/ContextMenuIconCheck.vue')['default']
    ContextMenuContextMenuIconRight: typeof import('./src/components/contextMenu/ContextMenuIconRight.vue')['default']
    ContextMenuContextMenuItem: typeof import('./src/components/contextMenu/ContextMenuItem.vue')['default']
    ContextMenuContextMenuSeparator: typeof import('./src/components/contextMenu/ContextMenuSeparator.vue')['default']
    ContextMenuContextSubMenu: typeof import('./src/components/contextMenu/ContextSubMenu.vue')['default']
    ContextMenuContextSubMenuWrapper: typeof import('./src/components/contextMenu/ContextSubMenuWrapper.vue')['default']
    DropdownDropdown: typeof import('./src/components/dropdown/dropdown.vue')['default']
    IconCopy: typeof import('@arco-design/web-vue/es/icon')['IconCopy']
    IconDown: typeof import('@arco-design/web-vue/es/icon')['IconDown']
    IconFolder: typeof import('@arco-design/web-vue/es/icon')['IconFolder']
    IconFullscreen: typeof import('@arco-design/web-vue/es/icon')['IconFullscreen']
    IconImport: typeof import('@arco-design/web-vue/es/icon')['IconImport']
    IconPaste: typeof import('@arco-design/web-vue/es/icon')['IconPaste']
    IconRedo: typeof import('@arco-design/web-vue/es/icon')['IconRedo']
    IconUndo: typeof import('@arco-design/web-vue/es/icon')['IconUndo']
    IconUpload: typeof import('@arco-design/web-vue/es/icon')['IconUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIconSvgIcon: typeof import('./src/components/svgIcon/svgIcon.vue')['default']
  }
}
